apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redises.redis.kfj.io
spec:
  group: redis.kfj.io
  names:
    kind: Redis
    listKind: RedisList
    plural: redises
    singular: redis
  scope: Namespaced
  version: v1alpha1
